// Kriging Interpolator (blog/tools/kriging-interpolator.qmd): the
// interactive layer around the page's hidden R cells (gstat), which fit
// a variogram to the uploaded sample points and krige a continuous
// surface. A ToolDashboard config.
import { ToolDashboard } from "../components/ToolDashboard.js";
import { base64ToFloat32 } from "../hooks/useToolData.js";
import { variogramSpec, pillifyReferenceLabels } from "./variogramChart.js";

// Brown (dry) to teal (wet): the samples and the surface share it.
const KRIGE_RAMP = [[0.00, 166, 97, 26], [0.25, 223, 194, 125], [0.50, 245, 245, 245], [0.75, 128, 205, 193], [1.00, 1, 133, 113]];
const POINT_COLORS = KRIGE_RAMP.map(([, r, g, b]) => `rgb(${r},${g},${b})`);
const EMPTY_STATS = [["Points", "—"], ["—", "Upload a point GeoJSON/Shapefile or load the example above"]];

// Points colored on the same ramp as the surface, over [min, max].
function circlePaint(min, max, field) {
  const step = (max - min) / 4;
  return {
    "circle-radius": 6,
    "circle-color": ["interpolate", ["linear"], ["get", field],
      min, POINT_COLORS[0], min + step, POINT_COLORS[1], min + step * 2, POINT_COLORS[2], min + step * 3, POINT_COLORS[3], max, POINT_COLORS[4]],
    "circle-stroke-color": "#2a2117",
    "circle-stroke-width": 1.5
  };
}

/** @type {import("../components/ToolDashboard.js").ToolConfig} */
const CONFIG = {
  tool: "kriging-interpolator",
  // 45 soil-moisture samples over a ~800 m × 600 m field, with a real
  // spatial trend (a wetter band and a ripple) under the noise: a
  // variogram with structure to find. Generated by
  // blog/examples/_make-kriging-soil-moisture.R.
  example: "/examples/kriging-soil-moisture.geojson",
  languages: ["r"],
  cells: { inspect: "kriging-interpolator-inspect-r", compute: "kriging-interpolator-compute-r" },
  exampleStatus: "✓ example soil-moisture samples loaded — pick the value column and Interpolate below.",
  inputs: [
    { kind: "select", name: "valueColumn", label: "Value column:", value: "", options: ({ inspect }) => inspect?.summary?.numericColumns ?? [] },
    { kind: "select", name: "variogramModel", label: "Model:", value: "Sph", options: ["Sph", "Exp", "Gau"] },
    { kind: "slider", name: "gridResolution", label: "Grid resolution", min: 10, max: 40, step: 5, value: 25 }
  ],
  inputsFromInspect: (value, inputs) => {
    const columns = value?.summary?.numericColumns ?? [];
    return { ...inputs, valueColumn: columns.includes("soil_moisture_pct") ? "soil_moisture_pct" : (columns[0] ?? "") };
  },
  computeLabel: "▶ Interpolate",
  busyLabel: "⌛ Kriging...",
  fit: { inspect: (v) => v.features },

  // The surface under the sample points; before Interpolate, the points
  // are colored by a preview of the likeliest value column.
  layers: ({ inspect, result }) => {
    const s = inspect?.summary;
    const preview = s && s.previewMin != null && s.previewMax != null;
    return [
      { id: "kriging-interpolator-surface", label: "Kriged surface", type: "raster",
        raster: result && { bounds: result.raster.wgs84Bounds, width: result.raster.width, height: result.raster.height,
          values: base64ToFloat32(result.raster.data), min: result.raster.min, max: result.raster.max, colorRamp: KRIGE_RAMP } },
      { id: "kriging-interpolator-points-r", label: "Samples", type: "circle",
        data: result?.samplePoints ?? inspect?.features ?? null,
        paint: result ? circlePaint(result.raster.min, result.raster.max, "value")
          : preview ? circlePaint(s.previewMin, s.previewMax, "previewValue") : undefined }
    ];
  },

  side: {
    id: "ki-chart",
    panels: [{
      kind: "chart",
      spec: ({ result }) => (result ? variogramSpec(result.variogram, result.summary) : null),
      onRender: pillifyReferenceLabels
    }]
  },

  stats: {
    empty: EMPTY_STATS,
    inspect: ({ summary: s }) => {
      if (!s) return EMPTY_STATS;
      return [
        ["Points", s.count.toLocaleString()],
        ["Original CRS", s.crs],
        ...(s.crsWarning ? [["CRS warning", s.crsWarning]] : []),
        ...(!s.numericColumns || s.numericColumns.length === 0 ? [["⚠️", "No numeric column found to interpolate"]] : [])
      ];
    },
    result: ({ summary: s }) => [
      ["Points used", s.count.toLocaleString()],
      ["Calculation CRS", s.calculationCrs],
      ["Value column", s.valueColumn],
      ["Variogram model", s.variogramModel],
      ["Nugget", s.nugget],
      ["Partial sill", s.partialSill],
      ["Range (m)", s.range],
      ["Grid cells", s.gridCellCount.toLocaleString()],
      ["Mean prediction", s.meanPrediction],
      ["Mean prediction variance", s.meanVariance]
    ]
  },
  legend: ({ inspect, result }) => {
    if (result) return { gradient: KRIGE_RAMP, minLabel: `${result.raster.min}%`, maxLabel: `${result.raster.max}%` };
    const s = inspect?.summary;
    return s && s.previewMin != null && s.previewMax != null
      ? { gradient: KRIGE_RAMP, minLabel: `${s.previewMin}%`, maxLabel: `${s.previewMax}%` }
      : null;
  },

  // The kriged surface as a GeoTIFF, for the inputs it was computed with.
  download: {
    cell: "kriging-interpolator-export-r",
    label: "⬇ Download GeoTIFF",
    inputs: ({ resultInputs: i }) => ({ valueColumn: i.valueColumn, variogramModel: i.variogramModel, gridResolution: i.gridResolution }),
    filename: () => "kriged-surface.tif",
    mimeType: "image/tiff"
  }
};

export const KrigingInterpolatorTool = () => <ToolDashboard config={CONFIG} />;
