// Raster Gap Filler (blog/tools/raster-gap-filler.qmd): the interactive
// layer around the page's hidden R cells (gstat), which fill the NoData
// pixels of one band by kriging, or by cokriging with a second band as
// covariate. A ToolDashboard config.
//
// Before Fill, the map previews the chosen bands and follows the menus:
// the target alone on a color ramp, or target and covariate as red and
// blue, so where each has gaps shows directly.
import { ToolDashboard } from "../components/ToolDashboard.js";
import { base64ToFloat32 } from "../hooks/useToolData.js";
import { gapFillerVariogramSpec, pillifyReferenceLabels } from "./variogramChart.js";

const FILL_RAMP = [[0.00, 68, 1, 84], [0.25, 59, 82, 139], [0.50, 33, 144, 140], [0.75, 94, 201, 98], [1.00, 253, 231, 37]];
const EMPTY_STATS = [["Dimensions", "—"], ["—", "Upload a multi-band .tif/.tiff file or load the example above"]];
const NONE = "None";

const bandCount = (inspect) => inspect?.summary?.bandCount ?? 0;
const bandNumbers = (inspect) => Array.from({ length: bandCount(inspect) }, (_, i) => String(i + 1));
const band = (inspect, n) => {
  const b = inspect?.bands?.find((x) => String(x.band) === String(n));
  return b && { values: base64ToFloat32(b.data), min: b.min, max: b.max };
};

/** @type {import("../components/ToolDashboard.js").ToolConfig} */
const CONFIG = {
  tool: "raster-gap-filler",
  // Two 25×25 bands of the same Gaussian hill, each with its own gap: a
  // 9×9 block in the target, a 3×3 one in the covariate partly inside
  // it, so all three cases show (covariate there, both missing, both
  // present). Generated by blog/examples/_make-gap-filler-two-bands.R.
  example: "/examples/gap-filler-two-bands.tif",
  uploadKind: "raster",
  languages: ["r"],
  cells: { inspect: "raster-gap-filler-inspect-r", compute: "raster-gap-filler-compute-r" },
  exampleStatus: "✓ example 2-band raster loaded — pick a target and (optionally) a covariate band, then Fill.",
  inputs: [
    { kind: "select", name: "targetBand", label: "Target:", value: "1", options: ({ inspect }) => bandNumbers(inspect) },
    { kind: "select", name: "covariateBand", label: "Covariate:", value: NONE, options: ({ inspect }) => [NONE, ...bandNumbers(inspect)] },
    { kind: "select", name: "variogramModel", label: "Model:", value: "Sph", options: ["Sph", "Exp", "Gau"] },
    { kind: "slider", name: "nmax", label: "Neighbourhood size", min: 10, max: 60, step: 2, value: 24 }
  ],
  // The band the file's own gaps suggest, and any other one as covariate.
  inputsFromInspect: (value, inputs) => {
    const n = value?.summary?.bandCount ?? 0;
    const target = value?.summary?.suggestedTarget ?? 1;
    const other = Array.from({ length: n }, (_, i) => i + 1).find((b) => b !== target);
    return { ...inputs, targetBand: String(target), covariateBand: n >= 2 && other ? String(other) : NONE };
  },
  computeLabel: "▶ Fill",
  busyLabel: "⌛ Kriging...",
  fit: { inspect: (v) => v.footprint },

  layers: ({ inspect, result }, { inputs }) => [
    { id: "raster-gap-filler-inspect-r", label: "Footprint", type: "fill", data: inspect?.summary ? inspect.footprint : null,
      paint: { "fill-color": "#42583c", "fill-opacity": 0.35, "fill-outline-color": "#2a2117" } },
    { id: "raster-gap-filler-compute-r", label: result ? "Filled band" : "Bands", type: "raster", ...rasterLayer(inspect, result, inputs) }
  ],

  side: {
    id: "rgf-chart",
    panels: [{ kind: "chart", spec: ({ result }) => (result?.variogram ? variogramFor(result) : null), onRender: pillifyReferenceLabels }]
  },

  stats: {
    empty: EMPTY_STATS,
    inspect: ({ summary: s }) => (s
      ? [
        ["Dimensions", `${s.width} × ${s.height} px`],
        ["Bands", String(s.bandCount)],
        ["CRS", s.crs],
        ["Per-band gaps", s.bandStats.map((b) => `Band ${b.band} (${b.name}): ${(b.naFraction * 100).toFixed(0)}% empty`).join(" · ")]
      ]
      : EMPTY_STATS),
    result: ({ summary: s }) => [
      ["Target band", String(s.targetBand)],
      ["Covariate band", s.covariateBand ? String(s.covariateBand) : "None (ordinary kriging)"],
      ["Variogram model", s.variogramModel],
      ["Nugget", s.nugget],
      ["Partial sill", s.partialSill],
      ["Range (px)", s.range],
      ["Sample mean", s.sampleMean],
      ["Sample variance", s.sampleVariance],
      ["Neighbourhood size", String(s.nmax)],
      ["Pixels filled", s.pixelsFilled.toLocaleString()],
      ...(s.crossValidationRmse != null ? [["Cross-validation RMSE", s.crossValidationRmse]] : []),
      ...(s.pixelsStillEmpty > 0 ? [["Still empty", `${s.pixelsStillEmpty.toLocaleString()} (no covariate data there either)`]] : []),
      ...(s.fitMethodFallback ? [["⚠️ Fit method", "fell back to a cruder weighting (Cressie's own fit failed on this data)"]] : [])
    ]
  },
  legend: ({ inspect, result }, { inputs }) => {
    if (result) return { gradient: FILL_RAMP, minLabel: `${result.raster.min}`, maxLabel: `${result.raster.max}` };
    const target = band(inspect, inputs.targetBand);
    if (!target) return null;
    return inputs.covariateBand !== NONE && band(inspect, inputs.covariateBand)
      ? [{ color: "rgb(255,0,0)", label: `Target (band ${inputs.targetBand})` }, { color: "rgb(0,0,255)", label: `Covariate (band ${inputs.covariateBand})` }]
      : { gradient: FILL_RAMP, minLabel: `${target.min}`, maxLabel: `${target.max}` };
  },

  // The filled band as a GeoTIFF, for the inputs it was filled with.
  download: {
    cell: "raster-gap-filler-export-r",
    label: "⬇ Download GeoTIFF",
    inputs: ({ resultInputs: i }) => ({ targetBand: i.targetBand, covariateBand: i.covariateBand, variogramModel: i.variogramModel, nmax: i.nmax }),
    filename: () => "gap-filled.tif",
    mimeType: "image/tiff"
  }
};

function rasterLayer(inspect, result, inputs) {
  if (result) {
    const r = result.raster;
    return { render: "ramp", raster: { bounds: r.wgs84Bounds, width: r.width, height: r.height, values: base64ToFloat32(r.data), min: r.min, max: r.max, colorRamp: FILL_RAMP } };
  }
  const target = band(inspect, inputs.targetBand);
  if (!target) return { raster: null };
  const s = inspect.summary;
  const base = { bounds: s.wgs84Bounds, width: s.width, height: s.height };
  const covariate = inputs.covariateBand !== NONE ? band(inspect, inputs.covariateBand) : null;
  return covariate
    ? { render: "bicolor", raster: { ...base, channelA: target, channelB: covariate } }
    : { render: "ramp", raster: { ...base, values: target.values, min: target.min, max: target.max, colorRamp: FILL_RAMP } };
}

// One panel for ordinary kriging; target, covariate and cross-variogram
// for cokriging.
function variogramFor({ variogram: v, summary: s }) {
  const panels = v.covariate
    ? [
      { label: `Target (band ${s.targetBand})`, color: "#e60000", data: v.target },
      { label: `Covariate (band ${s.covariateBand})`, color: "#0000e6", data: v.covariate },
      { label: "Cross (target × covariate)", color: "#a000a0", data: v.cross }
    ]
    : [{ label: `Target (band ${s.targetBand})`, color: "#ab502b", data: v.target }];
  return gapFillerVariogramSpec(panels, s.range);
}

export const RasterGapFillerTool = () => <ToolDashboard config={CONFIG} />;
