// Spatial Classifier tool (blog/tools/spatial-classifier.qmd): the
// interactive layer around the page's hidden Python cells. A
// ToolDashboard config; the cells, prose and URL are unchanged.
//
// Selection, a filter over the points:
//   { __key }                                    a map dot or a table row
//   { class }                                    a bar: every point of a class
//   { heldOut: true, class, predictedClass }     a matrix cell: the held-out
//                                                points behind it
// Any selection zooms to its points.
import { ToolDashboard } from "../components/ToolDashboard.js";
import { featureKey } from "../components/DataTable.js";
import { classifierChartSpec, chartKeyFor, selectionFromChartKey } from "./spatialClassifierChart.js";

const SRC = {
  grid: "spatial-classifier-grid-py",
  blocks: "spatial-classifier-blocks-py",
  points: "spatial-classifier-training-py"
};
const HOLDOUT_OPTIONS = ["Spatial blocks", "Random points"];
const EMPTY_STATS = [["Points", "—"], ["—", "Upload a point GeoJSON/Shapefile or load the example above"]];

// Same as WebGeoDS.Map's default circle style: uploaded, not yet classified.
const INSPECT_POINT_PAINT = {
  "circle-radius": 6,
  "circle-color": "#b0522c",
  "circle-stroke-width": 1,
  "circle-stroke-color": "#f3ede1"
};

const isHeldOut = ["==", ["get", "heldOut"], true];
// Held-out points are marked by the dashed blocks in blocks mode, by a
// thick ring around each point in random mode.
const blocksMode = (result) => (result?.summary.heldOutBlockCount ?? 0) > 0;

const CONFIG = {
  tool: "spatial-classifier",
  // 30 survey sites of 5 points each, three undulating bands, one site
  // in five on a local patch of another class: generated by
  // blog/examples/_make-spatial-classifier-survey.py, which explains why
  // it is sampled in sites (it's what makes the validation choice show).
  example: "/examples/spatial-classifier-survey.geojson",
  cells: {
    inspect: "spatial-classifier-inspect-py",
    compute: "spatial-classifier-compute-py",
    exportShp: "spatial-classifier-export-shp-py"
  },
  exampleStatus: "✓ example data loaded — pick the class column and Compute below.",
  inputs: [
    { kind: "select", name: "classColumn", label: "Class column:", value: "",
      options: ({ inspect }) => inspect?.summary?.columns ?? [] },
    // Blocks first and default: the cautious estimate for a map.
    { kind: "select", name: "holdout", label: "Held out:", options: HOLDOUT_OPTIONS, value: HOLDOUT_OPTIONS[0] },
    { kind: "slider", name: "nTrees", label: "Trees", min: 10, max: 300, step: 10, value: 100 },
    { kind: "slider", name: "gridResolution", label: "Grid resolution", min: 10, max: 40, step: 5, value: 20 }
  ],
  // Default class column: "class" if the file has one, else the first.
  inputsFromInspect: (value, inputs) => {
    const columns = value?.summary?.columns ?? [];
    return { ...inputs, classColumn: columns.includes("class") ? "class" : (columns[0] ?? "") };
  },
  busyLabel: "⌛ Training...",
  fit: { inspect: (v) => v.features },

  selectable: {
    id: SRC.points,
    from: ({ inspect, result }) => result?.trainingFeatures ?? inspect?.features ?? null,
    layer: "spatial-classifier-selection",
    paint: ({ result }) => ({ "circle-stroke-width": blocksMode(result) ? 0 : ["case", isHeldOut, 3, 0] }),
    fit: true
  },

  layers: ({ inspect, result }, { selection }) => {
    // MapLibre hands back its own copy of the feature, with a numeric id;
    // featureKey normalizes it to the key the data has.
    const points = {
      id: SRC.points, label: "Points", type: "circle",
      data: result?.trainingFeatures ?? inspect?.features ?? null,
      selectBy: (feature) => ({ __key: featureKey(SRC.points, feature, -1) })
    };
    if (!result) return [{ ...points, paint: INSPECT_POINT_PAINT }];

    const palette = window.WebGeoDS.DEFAULT_PALETTE;
    const labels = result.summary.classLabels;
    // A matrix cell selects only held-out points: fade the training ones
    // so they don't compete with them. Not for a class: it has both.
    const fadeTraining = selection?.predictedClass !== undefined;
    return [
      {
        id: SRC.grid, label: "Classification areas", type: "fill", data: result.gridFeatures,
        paint: {
          ...window.WebGeoDS.matchPaint(labels, "predictedClass", { palette, fill: true, strokeWidth: 1.5 }),
          // Opacity carries the forest's confidence: nearly transparent
          // at 1/n_classes (trees split evenly), solid where all agree.
          "fill-opacity": ["interpolate", ["linear"], ["get", "confidence"], 1 / labels.length, 0.08, 1, 0.6]
        }
      },
      {
        id: SRC.blocks, label: "Held-out blocks", type: "line", data: result.heldOutBlockFeatures,
        paint: { "line-color": "#2a2117", "line-width": 2, "line-dasharray": [2, 1.5] }
      },
      {
        ...points,
        paint: {
          ...window.WebGeoDS.matchPaint(labels, "class", { palette, strokeWidth: 1.5 }),
          "circle-stroke-width": blocksMode(result) ? 1.5 : ["case", isHeldOut, 3, 1.5],
          "circle-opacity": fadeTraining ? ["case", isHeldOut, 1, 0.12] : 1
        }
      }
    ];
  },

  side: {
    id: "sc-chart",
    panels: [{
      kind: "chart",
      spec: ({ result }) => (result ? classifierChartSpec(result.summary) : null),
      selectParams: ["classSelectDist", "classSelectAcc"], externalParam: "classExternal", keyField: "key",
      toKey: chartKeyFor,
      fromKey: selectionFromChartKey
    }]
  },

  // Right under the map and legend, before the notes.
  tables: [
    { label: "Training points", id: SRC.points, from: ({ inspect, result }) => result?.trainingFeatures ?? inspect?.features },
    { label: "Classification areas", id: SRC.grid, from: ({ result }) => result?.gridFeatures }
  ],

  stats: { empty: EMPTY_STATS, inspect: inspectStats, result: (result) => computeStats(result.summary) },

  legend: ({ result }) => result && [
    ...result.summary.classLabels.map((label, i) => ({
      color: window.WebGeoDS.DEFAULT_PALETTE[i % window.WebGeoDS.DEFAULT_PALETTE.length],
      label
    })),
    // One "held out" entry, drawn the way the map draws it in this mode.
    blocksMode(result)
      ? { color: "#2a2117", label: "held out for testing (points inside)", outline: "dashed" }
      : { color: "#2a2117", label: "held out for testing", outline: true, shape: "circle" }
  ],

  download: {
    getFeatures: (result) => result.originalCrsFeatures,
    filenameSuffix: "-classified-surface.geojson",
    defaultFilename: "classified-surface.geojson",
    shapefile: { filenameSuffix: "-classified-surface.zip", defaultFilename: "classified-surface-shapefile.zip" }
  }
};

export const SpatialClassifierTool = () => <ToolDashboard config={CONFIG} />;

function inspectStats(value) {
  const s = value.summary;
  if (!s) return EMPTY_STATS;
  const rows = [
    ["Points", s.count.toLocaleString()],
    ["Original CRS", s.crs === "None" || !s.crs ? "Unknown" : s.crs]
  ];
  if (value.crsWarning) rows.push(["CRS warning", value.crsWarning]);
  return rows;
}

function computeStats(r) {
  // Python's None arrives as `undefined`, not `null`: loose equality
  // catches both.
  const pct = (x, digits = 0) => (x == null ? "N/A" : `${(x * 100).toFixed(digits)}%`);
  const metres = (x) => (x == null ? "N/A" : `${Math.round(x).toLocaleString()} m`);
  const rows = [
    ["Points", r.count.toLocaleString()],
    ["Original CRS", r.crs === "None" || !r.crs ? "Unknown" : r.crs],
    ["Calculation CRS", r.calculationCrs],
    ["Class column", r.classColumn],
    ["Classes found", r.classLabels.join(", ")],
    ["Labeled points", r.labeledCount.toLocaleString()]
  ];
  if (r.excludedCount > 0) {
    rows.push(["Excluded from training", `${r.excludedCount} (too far from the calculation UTM zone to project)`]);
  }
  rows.push([
    "Held out",
    r.testCount === 0 ? "—"
      : r.holdout === "Spatial blocks"
        ? `${r.testCount} points in ${r.heldOutBlockCount} of ${r.blocksPerSide * r.blocksPerSide} blocks (dashed on the map)`
        : `${r.testCount} random points`
  ]);
  rows.push(["Train / test split", r.testCount > 0 ? `${r.trainCount} / ${r.testCount}` : `${r.trainCount} / — (too few points to hold out)`]);
  rows.push(["Test accuracy", pct(r.accuracy, 1)]);
  rows.push(["5-fold CV accuracy", `random points ${pct(r.cvRandom)} · spatial blocks ${pct(r.cvBlocks)}`]);
  rows.push([
    "Distance to nearest sample",
    `map cells ${metres(r.distanceMap)} · random test ${metres(r.distanceRandom)} · block test ${metres(r.distanceBlocks)} (medians)`
  ]);
  rows.push(["Trees", r.nTrees]);
  rows.push(["Grid cells", r.gridCellCount.toLocaleString()]);
  rows.push(["Mean confidence", pct(r.meanConfidence)]);
  rows.push([
    "Uncertain cells",
    `${r.uncertainCellCount.toLocaleString()} (${(r.uncertainCellCount / r.gridCellCount * 100).toFixed(0)}%) under ${(r.uncertainBelow * 100).toFixed(0)}% agreement`
  ]);
  return rows;
}
