/**
 * WebGeoDS.Dashboard
 *
 * Owns the whole upload/example -> inspect -> compute -> map/stats/
 * legend/download/reset skeleton that every hand-wired tool `.qmd`
 * page currently repeats as ~20 OJS cells, so a new tool can be built
 * from a declarative config instead of an analyst having to learn OJS
 * reactivity (`mutable`, cell dependency wiring) to build one.
 *
 * A plain JS class, not an OJS-reactive construct -- same principle as
 * WebGeoDSMap/WebGeoDSCodeCell already use: internal state is a normal
 * object, re-rendered imperatively on change, not a `mutable`. This
 * works because WebGeoDSCodeCell.run() (code-cell.js) already returns
 * its result directly and rejects on error -- strictly more than OJS's
 * getCellValue()/Generators.observe() gives you (a Generator can't
 * surface a Python/R traceback). Investigated and confirmed empirically
 * this session, reading buffer-proximity.qmd and crs-inspector.qmd in
 * full: in every existing tool, the actual *compute* step (as opposed
 * to the initial inspect-after-upload step) is ALREADY imperative --
 * triggered by a click, awaiting CodeCell.run(), reading the result
 * from its return value -- never OJS-reactive. Only the inspect step
 * used getCellValue()/Generators in the tools examined. Dashboard
 * generalizes what was already the imperative common case, and needs
 * zero `mutable`, zero `Generators`, zero `{ojs}` cell to exist at all.
 *
 * Mount as a plain `<div>` + `<script>` on DOMContentLoaded, not an
 * `{ojs}` cell:
 *
 *   <div id="my-dashboard"></div>
 *   <script>
 *   document.addEventListener("DOMContentLoaded", () => {
 *     new WebGeoDS.Dashboard({ tool: "my-tool", mount: "#my-dashboard", ... });
 *   });
 *   </script>
 *
 * Two independent reasons, not just simplicity: (1) Quarto's OJS
 * runtime is a deferred module, so an `{ojs}` cell's body executes
 * BEFORE DOMContentLoaded -- exactly when webgeods-cells.lua's own
 * generated CodeCells are still being constructed (see that file's own
 * `document.addEventListener("DOMContentLoaded", ...)` wrapper).
 * Mounting Dashboard on the same event as the CodeCells it drives
 * removes that race at the source, rather than working around it.
 * (2) A deferred future phase wants a declarative, non-JS syntax for
 * this config, generated by a Lua filter -- and a Lua filter CANNOT
 * synthesize a reactive `{ojs}` block Quarto will actually execute
 * (confirmed already failed once, see webgeods-cells.lua's own
 * docstring on this exact point). It CAN emit the `<div>+<script>` raw
 * HTML shape above, because that's exactly the mechanism already in
 * production for `.webgeods-python`/`.webgeods-r` cells. Mounting this
 * way now means that future filter only has to emit the same shape it
 * already knows how to emit, not a new and harder problem.
 *
 * Every tool-specific hook in the config is a pure function of a code
 * cell's return value (`value => ...`) -- no DOM, no reactivity, no
 * OJS concept an analyst has to learn beyond "return some rows".
 *
 * Config shape:
 *
 *   new WebGeoDS.Dashboard({
 *     tool: "network-from-lines",     // tracking id + Dashboard.find() key
 *     mount: "#my-dashboard",         // CSS selector or HTMLElement
 *     map: { center: [12.45, 41.9], zoom: 4 }, // height optional --
 *           defaults to DEFAULT_MAP_HEIGHT below, override only if a
 *           tool genuinely needs something else,
 *     upload: { languages: ["python"], kind: "vector", label: "📁 Upload" },
 *     resetLabel: "🔄 Reset", // optional -- the Reset button always
 *                  exists (same control row as upload/example/
 *                  download), this only overrides its label; no
 *                  dedicated `reset: {...}` block since there's
 *                  nothing else to configure about it.
 *     example: { cellId: "my-example-py", kind: "geojson",
 *                status: "✓ example data loaded." },
 *     inspect: { cellId: "my-inspect-py",
 *                layers: [{ source, from, type, paint, fit, onClick }],
 *                stats: value => [["Label", value]] },
 *     compute: { cellId: "my-compute-py", label: "▶ Compute",
 *                busyLabel: "⌛ Working...",
 *                inputs: [{ kind: "slider"|"checkbox"|"select", name,
 *                           label, range: [min,max], value, step, //
 *                           slider
 *                           options: inspectValue => [...], // select
 *                           only -- repopulated every time inspect
 *                           completes (see _syncSelectInputs() below),
 *                           since a select's options (unlike a
 *                           slider's fixed range) usually depend on
 *                           what was actually uploaded
 *                           default: inspectValue => "preferred" }], //
 *                           select only, optional
 *                layers: [{ source, from, type, paint, fit, onClick }],
 *                stats: (value, inputs) => [["Label", value]],
 *                legend: value => [{ color, label }],
 *                download: { getFeatures: value => featureCollection,
 *                            filenameSuffix, defaultFilename,
 *                            shapefile: { cellId, filenameSuffix,
 *                            defaultFilename } }, // optional -- same
 *                            `shapefile` option downloadButton() itself
 *                            takes (shared/ui.js), minus `uploadKind`
 *                            (Dashboard supplies that live from its own
 *                            state, see _buildDom() below). Lives under
 *                            `compute`, not as a sibling of upload/
 *                            example, even though its BUTTON renders in
 *                            the same control row as theirs -- a real
 *                            data dependency, not just an organizing
 *                            choice: `getFeatures` operates on the
 *                            COMPUTE value, so its config travels with
 *                            the step that produces what it downloads.
 *                diagram: { nodes: value => features, links: value =>
 *                           features, ...renderForceGraph()'s own
 *                           options (nodeColor, onNodeClick, ...) },
 *                           // optional, needs layout.sidePanel AND
 *                           // graph-diagram.js loaded -- see
 *                           // _renderDiagram() below.
 *                onResult: (value, inputs) => { ... } } // optional --
 *                an escape hatch for anything NOT expressible as a
 *                pure function of the compute value (layers/stats/
 *                legend/diagram all are); called with `null` on reset.
 *   })
 *
 * `layers[].type` ("circle"|"line"|"fill") is required, not inferred:
 * WebGeoDSMap._detectGeometryType() falls back to "fill" for an empty
 * FeatureCollection (map.js), which would silently flip a cleared
 * circle/line layer to "fill" on reset -- declaring the type up front
 * and passing it explicitly on every setGeoJSON()/clear call sidesteps
 * that instead of relying on inference to guess right on an empty set.
 *
 * `layers[].onClick(feature)` -- optional, the declarative counterpart
 * to renderForceGraph()'s own `onNodeClick` (graph-diagram.js): fires
 * with the clicked GeoJSON feature, letting a tool cross-link a map
 * layer to a diagram/table/chart the same way it would cross-link the
 * diagram's own nodes, without reaching into `.map.map` itself after
 * `ready()`. Attached once per source, the first time that layer is
 * rendered -- safe to declare on a layer that gets re-rendered by
 * every Compute run.
 *
 * No ES module syntax so this can be included directly by Quarto.
 */

(() => {

  "use strict";


  window.WebGeoDS =
    window.WebGeoDS || {};


  // ============================================================
  // DEFAULT_MAP_HEIGHT -- clamp(), not a fixed pixel value: scales
  // with the viewport instead of always taking exactly one height
  // regardless of how tall the screen actually is. shared/map.js
  // already watches the container with a ResizeObserver and calls
  // MapLibre's own resize() on any change (see its "Automatic resize"
  // comment) -- it doesn't care WHY the box changed size, so a
  // CSS-driven height like this one needs no change there to be
  // picked up correctly, including on a window resize/orientation
  // change after the page has already loaded. A Dashboard-level
  // default, not createSharedMap()'s own ("480px", shared/ui.js): that
  // one is used by every hand-wired tool already shipped sitewide, a
  // much bigger blast radius than changing what's new here defaults
  // to. Still just a default -- a tool with unusual needs overrides
  // it via `map: { height: "..." }` like any other config field.
  // ============================================================

  const DEFAULT_MAP_HEIGHT =
    "clamp(320px, 55vh, 480px)";


  // ============================================================
  // Instance registry -- same role as WebGeoDSMap's/WebGeoDSCodeCell's
  // own _instances/find(), keyed by the config's `tool` id.
  // ============================================================

  const _instances = new Map();


  // ============================================================
  // WebGeoDSDashboard
  // ============================================================

  class WebGeoDSDashboard {


    // ----------------------------------------------------------
    // find(tool) -- look up a live instance by its `tool` id
    // ----------------------------------------------------------

    static find(tool) {

      return _instances.get(tool);

    }


    // ----------------------------------------------------------
    // Constructor -- synchronous DOM build, async init kicked off
    // and tracked via this.isReady (same pattern as WebGeoDSMap/
    // WebGeoDSCodeCell: the instance and its DOM exist immediately,
    // only the map/CodeCell wiring is awaited).
    // ----------------------------------------------------------

    constructor(config) {

      if (!config || !config.tool) {

        throw new TypeError(
          "WebGeoDS.Dashboard: config.tool is required."
        );

      }

      this.config =
        config;

      this.state = {
        status: window.WebGeoDS.Upload.defaultStatus,
        busy: false,
        files: null,
        kind: null,
        inspectValue: null,
        result: null,
        inputs: {}
      };

      // Every async entry point (loadExample/handleFiles/runCompute/
      // reset) chains off this single promise instead of running
      // concurrently -- CodeCell.run() throws "the cell is already
      // running" on overlap (code-cell.js), which a double-click or an
      // upload arriving mid-compute would otherwise hit.
      this._chain =
        Promise.resolve();

      this._inputEls =
        {};

      // Tracks which layer sources already have a click listener
      // attached (see _renderLayers()'s `spec.onClick`) -- a layer
      // persists across repeated Compute runs (setGeoJSON updates its
      // data in place, same source id every time), so the listener
      // must be attached once, not once per run.
      this._clickBoundLayers =
        new Set();

      // See _renderDiagram() -- the optional compute.diagram slot.
      this._diagram =
        null;

      _instances.set(
        config.tool,
        this
      );

      this._buildDom();

      this.isReady =
        this._init();

    }


    // ----------------------------------------------------------
    // ready()
    // ----------------------------------------------------------

    async ready() {

      await this.isReady;

    }


    // ----------------------------------------------------------
    // Accessors
    // ----------------------------------------------------------

    get el() {

      return this.root;

    }

    get map() {

      return this._map || null;

    }

    // The renderForceGraph() handle from compute.diagram (null if
    // that config option isn't used, or before the first successful
    // Compute) -- same reasoning as `map` above: exposed so a tool
    // can drive it externally (e.g. dashboard.diagram?.setSelected(id)
    // from a map-click handler), not just read it.
    get diagram() {

      return this._diagram || null;

    }

    // The DOM node the map lives in -- exposed so a tool-specific
    // add-on (e.g. a diagram panel, see graph-diagram.js) can
    // reposition it (typically: pull it into a flex row alongside
    // itself) without Dashboard needing an opinion on that layout.
    get mapEl() {

      return this.mapSlotEl;

    }

    // Note: `sidePanelEl` itself is a plain property (set directly in
    // _buildDom(), left undefined if layout.sidePanel wasn't
    // configured), not a getter -- same convention as statsEl/
    // legendWrapEl, which have never needed one either.

    get value() {

      return this.state.result;

    }

    get inspectValue() {

      return this.state.inspectValue;

    }


    // ==========================================================
    // DOM construction
    // ==========================================================

    _buildDom() {

      const config =
        this.config;

      this.root =
        document.createElement("div");

      this.root.className =
        "webgeods-dashboard";


      // --------------------------------------------------------
      // Control panel: upload, example, download, reset -- one row --
      // then a status row, then (if this tool has compute inputs) a
      // third row for those + the Compute button.
      // --------------------------------------------------------

      const panel =
        document.createElement("div");

      panel.className =
        "webgeods-panel";

      const controlRow =
        document.createElement("div");

      controlRow.className =
        "webgeods-panel-row";

      const controlChildren = [];

      const uploadCfg =
        config.upload || {};

      this._uploadControl =
        window.WebGeoDS.Upload.createControl({
          label: uploadCfg.label || "📁 Upload",
          kind: uploadCfg.kind || "vector",
          onChange: (files) => this.handleFiles(files)
        });

      controlChildren.push(this._uploadControl);

      if (config.example) {

        this._exampleBtn =
          document.createElement("button");

        this._exampleBtn.className =
          "webgeods-panel-btn";

        this._exampleBtn.dataset.variant =
          "outline";

        this._exampleBtn.textContent =
          config.example.label || "📋 Load example";

        this._exampleBtn.onclick =
          () => this.loadExample();

        controlChildren.push(this._exampleBtn);

      }

      if (config.compute && config.compute.download) {

        const downloadCfg =
          config.compute.download;

        const dashboard =
          this;

        this._downloadBtn =
          window.WebGeoDS.downloadButton({
            getFeatures: () => downloadCfg.getFeatures(this.state.result),
            getBaseName: () => window.WebGeoDS.Upload.baseName(this.state.files),
            filenameSuffix: downloadCfg.filenameSuffix,
            defaultFilename: downloadCfg.defaultFilename,
            enabled: false,
            tool: config.tool,
            mimeType: downloadCfg.mimeType,
            // `uploadKind` as a GETTER, not a frozen value: this button
            // is built once in the constructor and never rebuilt (see
            // this file's own doc comment on compute inputs), but the
            // upload kind changes on every upload/example load after
            // that -- a plain property would freeze it at its initial
            // value (null) forever. downloadButton() (shared/ui.js)
            // reads shapefile.uploadKind fresh on every click, so a
            // getter transparently stays current with no change needed
            // there.
            shapefile: downloadCfg.shapefile ? {
              ...downloadCfg.shapefile,
              get uploadKind() { return dashboard.state.kind; }
            } : undefined
          });

        controlChildren.push(this._downloadBtn);

      }

      this._resetBtn =
        window.WebGeoDS.resetButton(
          () => this.reset(),
          config.resetLabel || "🔄 Reset"
        );

      controlChildren.push(this._resetBtn);

      controlRow.append(...controlChildren);


      const statusRow =
        document.createElement("div");

      statusRow.className =
        "webgeods-panel-row";

      this.statusRowEl =
        statusRow;

      statusRow.appendChild(
        window.WebGeoDS.uploadStatusEl(this.state.status, this.state.busy)
      );


      panel.append(controlRow, statusRow);


      // --------------------------------------------------------
      // Compute inputs row (sliders/checkboxes) + Compute button --
      // built once, not rebuilt on state changes (a real bug in
      // hand-wired tools: buffer-proximity.qmd's own controls row
      // rebuilds whenever inspectSummary changes, silently resetting
      // any slider the reader had already moved). Only disabled/
      // enabled afterward, via _syncControls().
      // --------------------------------------------------------

      if (config.compute) {

        const computeRow =
          document.createElement("div");

        computeRow.className =
          "webgeods-panel-row";

        for (const input of (config.compute.inputs || [])) {

          if (input.kind === "checkbox") {

            const wrap =
              document.createElement("label");

            wrap.className =
              "webgeods-panel-status";

            const checkbox =
              document.createElement("input");

            checkbox.type =
              "checkbox";

            checkbox.checked =
              !!input.value;

            wrap.append(
              checkbox,
              document.createTextNode(" " + input.label)
            );

            computeRow.appendChild(wrap);

            this._inputEls[input.name] =
              checkbox;

          } else if (input.kind === "select") {

            // Built empty here -- unlike a slider's range, a select's
            // OPTIONS aren't known until inspect actually runs (e.g.
            // "which column holds the class label" depends on the
            // uploaded file's own attribute columns). See
            // _syncSelectInputs(), called from _runInspectInner()
            // below, for where the options actually get populated.
            const label =
              document.createElement("span");

            label.className =
              "webgeods-panel-status";

            label.textContent =
              input.label;

            const select =
              document.createElement("select");

            select.className =
              "webgeods-panel-status";

            select.id =
              `${config.tool}-${input.name}`;

            computeRow.append(
              label,
              select
            );

            this._inputEls[input.name] =
              select;

          } else {

            const sliderWrap =
              window.WebGeoDS.createSlider(
                input.range,
                {
                  value: input.value,
                  step: input.step,
                  label: input.label,
                  id: `${config.tool}-${input.name}`
                }
              );

            computeRow.appendChild(sliderWrap);

            this._inputEls[input.name] =
              sliderWrap.querySelector("input");

          }

        }

        this._computeBtn =
          document.createElement("button");

        this._computeBtn.className =
          "webgeods-panel-btn";

        this._computeBtn.textContent =
          config.compute.label || "▶ Compute";

        this._computeBtn.disabled =
          true;

        this._computeBtn.onclick =
          () => this.runCompute();

        computeRow.appendChild(this._computeBtn);

        panel.appendChild(computeRow);

      }


      // --------------------------------------------------------
      // Stats / map / legend, outside the panel -- same document
      // order as every hand-wired tool (summary read before the map,
      // legend after it).
      // --------------------------------------------------------

      this.statsEl =
        document.createElement("div");

      this.mapSlotEl =
        document.createElement("div");

      this.legendWrapEl =
        document.createElement("div");

      this._renderStats();

      this.legendWrapEl.appendChild(
        window.WebGeoDS.legend(null)
      );

      // layout.sidePanel: an EXTRA slot beside the map, for a tool
      // that wants a second view next to it (e.g. a diagram, see
      // graph-diagram.js) without hand-wiring the DOM surgery this
      // itself replaces -- moving mapSlotEl into a flex row, matching
      // its height, and fixing the two layout bugs that surgery hit
      // in practice: (1) a flex item traps its child's margin instead
      // of letting it collapse through, which silently ate the normal
      // gap .webgeods-map-container's own margin-top provides above
      // the stat card -- worked around here by moving that spacing
      // onto the row itself, a plain block sibling that isn't anybody
      // else's flex item; (2) the same trapped margin also inflated
      // mapSlotEl's own rendered height beyond the map's actual
      // content height, misaligning it against the side panel -- the
      // real fix is removing the trap at its source (zeroing the
      // map's own margin-top once it exists, in _init() below), not
      // re-measuring around it.
      const sidePanelCfg =
        config.layout?.sidePanel;

      if (sidePanelCfg) {

        this._mapRow =
          document.createElement("div");

        this._mapRow.style.cssText =
          "display: flex; gap: 16px; flex-wrap: wrap; align-items: flex-start; margin-top: 20px;";

        this.sidePanelEl =
          document.createElement("div");

        if (sidePanelCfg.id) {

          this.sidePanelEl.id =
            sidePanelCfg.id;

        }

        const mapHeight =
          config.map?.height ?? DEFAULT_MAP_HEIGHT;

        this.sidePanelEl.style.cssText =
          `flex: ${sidePanelCfg.flex ?? "1 1 280px"}; min-width: ${sidePanelCfg.minWidth ?? "260px"}; height: ${mapHeight}; overflow: hidden; border: 1px solid #d8cdb8; border-radius: 4px;`;

        this.mapSlotEl.style.flex =
          "2 1 480px";

        this._mapRow.append(this.mapSlotEl, this.sidePanelEl);

      }

      this.root.append(
        panel,
        this.statsEl,
        sidePanelCfg ? this._mapRow : this.mapSlotEl,
        this.legendWrapEl
      );


      // --------------------------------------------------------
      // Mount
      // --------------------------------------------------------

      const mount =
        config.mount;

      if (typeof mount === "string") {

        const target =
          document.querySelector(mount);

        if (!target) {

          throw new Error(
            `WebGeoDS.Dashboard: mount "${mount}" not found.`
          );

        }

        target.appendChild(this.root);

      } else if (mount instanceof HTMLElement) {

        mount.appendChild(this.root);

      }

      // No `mount` given: root stays detached, available via `.el` for
      // the caller to place itself.

    }


    // ==========================================================
    // Async init -- the map (the one piece that's genuinely async
    // before anything can render into it).
    // ==========================================================

    async _init() {

      this._map =
        await window.WebGeoDS.createSharedMap({
          tool: this.config.tool,
          height: DEFAULT_MAP_HEIGHT,
          ...(this.config.map || {})
        });

      this.mapSlotEl.appendChild(
        this._map.element
      );

      // See the layout.sidePanel comment in _buildDom() -- only
      // reachable now, once the map element this margin lives on
      // actually exists.
      if (this.config.layout?.sidePanel) {

        this._map.element.style.marginTop =
          "0";

      }

    }


    // ==========================================================
    // _cell(id) -- lazy CodeCell resolution.
    //
    // Never called from the constructor/_init: an {.webgeods-python}
    // cell is constructed by webgeods-cells.lua's own
    // DOMContentLoaded listener, which can fire after or before this
    // class's own mounting script depending on document order --
    // resolving lazily, on first actual use (a click, always after
    // the page has finished loading), sidesteps needing to reason
    // about that ordering at all.
    // ==========================================================

    async _cell(id) {

      let cell =
        window.WebGeoDS.CodeCell.find(id);

      if (cell) {

        return cell;

      }

      if (document.readyState === "loading") {

        await new Promise((resolve) =>
          document.addEventListener("DOMContentLoaded", resolve, { once: true })
        );

        cell =
          window.WebGeoDS.CodeCell.find(id);

      }

      if (!cell) {

        throw new Error(
          `WebGeoDS.Dashboard: code cell "${id}" not found — check the {.webgeods-python #${id}} block exists in this page.`
        );

      }

      return cell;

    }


    // ==========================================================
    // _queue(label, fn) -- serializes every entry point through one
    // chain, so a click arriving while a previous run is still in
    // flight waits its turn instead of hitting CodeCell's own
    // "already running" error.
    // ==========================================================

    _queue(label, fn) {

      this._chain =
        this._chain.then(async () => {

          this._setStatus(label, { busy: true });
          this._syncControls();

          try {

            await fn();

          } catch (err) {

            console.error(
              `WebGeoDS.Dashboard (${this.config.tool}): ${label} failed`,
              err
            );

            this._setStatus(
              `⚠️ ${label} failed: ${err.message}`,
              { busy: false }
            );

          } finally {

            this.state.busy =
              false;

            this._syncControls();

          }

        });

      return this._chain;

    }


    // ==========================================================
    // loadExample() -- runs the example-generating cell (Python code
    // that writes its own file into the VFS, same convention every
    // hand-wired tool's generateExample() already uses), then
    // inspects it.
    // ==========================================================

    async loadExample() {

      return this._queue("⌛ Loading example...", async () => {

        const cfg =
          this.config.example;

        const cell =
          await this._cell(cfg.cellId);

        await cell.run();

        this.state.kind =
          cfg.kind || "geojson";

        await this._runInspectInner();

        this.state.status =
          cfg.status || "✓ example data loaded — ready to build below.";

      });

    }


    // ==========================================================
    // handleFiles(files) -- the upload control's onChange.
    // ==========================================================

    async handleFiles(files) {

      return this._queue("⌛ Loading...", async () => {

        const uploadCfg =
          this.config.upload || {};

        const result =
          await window.WebGeoDS.Upload.load(files, {
            languages: uploadCfg.languages || ["python"]
          });

        this.state.files =
          files;

        if (!result.ok) {

          this.state.status =
            result.message;

          return;

        }

        this.state.kind =
          result.kind;

        await this._runInspectInner();

        this.state.status =
          result.message;

      });

    }


    // ==========================================================
    // _runInspectInner() -- shared by loadExample()/handleFiles(),
    // both of which already run inside _queue(). New data
    // invalidates any prior compute result, same reasoning every
    // hand-wired tool's own pyInspect reactive block already applies.
    // ==========================================================

    async _runInspectInner() {

      const cfg =
        this.config.inspect;

      const cell =
        await this._cell(cfg.cellId);

      const value =
        await cell.run();

      this.state.inspectValue =
        value;

      this.state.result =
        null;

      await this._clearLayers(this.config.compute && this.config.compute.layers);

      await this._renderLayers(cfg.layers, value);

      this._renderStats();
      this._renderLegend();
      this._syncSelectInputs(value);

    }


    // A select-kind input's OPTIONS depend on the inspect value (e.g.
    // "which attribute columns exist"), unlike a slider's fixed range
    // -- repopulated here every time inspect completes, instead of
    // once in _buildDom() like every other input kind.
    _syncSelectInputs(inspectValue) {

      for (const input of (this.config.compute?.inputs || [])) {

        if (input.kind !== "select") {

          continue;

        }

        const el =
          this._inputEls[input.name];

        if (!el) {

          continue;

        }

        const options =
          inspectValue && input.options ? input.options(inspectValue) : [];

        el.replaceChildren(
          ...options.map((opt) => new Option(opt, opt))
        );

        const preferred =
          inspectValue && input.default ? input.default(inspectValue) : undefined;

        if (preferred !== undefined && options.includes(preferred)) {

          el.value =
            preferred;

        }

      }

    }


    // ==========================================================
    // runCompute() -- imperative end to end: reads the live input
    // values, injects them as `window[name]` (same mechanism `#|
    // inject:` reads from, see code-cell.js's buildInjectPreamble),
    // runs the compute cell, uses its RETURN VALUE directly -- never
    // `.value`, never getCellValue/Generators.
    // ==========================================================

    async runCompute() {

      const cfg =
        this.config.compute;

      return this._queue(cfg.busyLabel || "⌛ Working...", async () => {

        this.state.inputs =
          this._readInputs();

        for (const [name, value] of Object.entries(this.state.inputs)) {

          window[name] =
            value;

        }

        const cell =
          await this._cell(cfg.cellId);

        const value =
          await cell.run();

        this.state.result =
          value;

        await this._renderLayers(cfg.layers, value, this.state.inputs);

        this._renderStats();
        this._renderLegend();
        this._renderDiagram(cfg.diagram, value);

        // Extension point for anything Dashboard itself still doesn't
        // know about -- everything expressible as "a pure function of
        // the compute value" (a layer, a stat row, a legend swatch, a
        // diagram) has its own declarative field now; onResult is only
        // for a tool-specific escape hatch beyond that.
        cfg.onResult?.(value, this.state.inputs);

        window.WebGeoDS.track?.("validation_completed", { tool: this.config.tool });

        // `this.state.status` was already overwritten with `cfg.
        // busyLabel` at the top of _queue() -- falling back to it here
        // would just re-set the same busy text, leaving it stuck
        // forever (a real bug, found live: the button bar kept
        // reading "Building..." long after the build had finished).
        this.state.status =
          cfg.doneMessage || "✓ Done.";

      });

    }


    // ==========================================================
    // reset() -- clears every declared layer (inspect's and
    // compute's), state, stats, legend and download-enabled state,
    // WITHOUT touching the Python/R engine.
    // ==========================================================

    async reset() {

      return this._queue("Resetting...", async () => {

        await this._clearLayers(this.config.inspect && this.config.inspect.layers);
        await this._clearLayers(this.config.compute && this.config.compute.layers);

        this.state.inspectValue =
          null;

        this.state.result =
          null;

        this.state.files =
          null;

        this.state.kind =
          null;

        this._renderStats();
        this._renderLegend();
        this._renderDiagram(this.config.compute?.diagram, null);

        // Same onResult hook runCompute() calls, with `null` -- lets
        // a tool-specific escape hatch clear itself on reset too.
        this.config.compute?.onResult?.(null);

        this.state.status =
          window.WebGeoDS.Upload.defaultStatus;

      });

    }


    // ==========================================================
    // Layer rendering / clearing
    // ==========================================================

    async _renderLayers(specs, value, inputs) {

      if (!specs || !value) {

        return;

      }

      for (const spec of specs) {

        const features =
          spec.from(value);

        const paint =
          spec.paint ? spec.paint(value, inputs) : undefined;

        await this._map.setGeoJSON(
          spec.source,
          features,
          { type: spec.type, ...(paint ? { paint } : {}) }
        );

        if (spec.fit) {

          await this._map.fitToData(features);

        }

        // Declarative counterpart to renderForceGraph()'s own
        // onNodeClick (graph-diagram.js) -- a layer spec can name a
        // callback right next to its from/type/paint instead of the
        // caller reaching into `.map.map` itself after ready().
        // Attached once per source (see _clickBoundLayers above), not
        // once per Compute run.
        if (spec.onClick && !this._clickBoundLayers.has(spec.source)) {

          this._clickBoundLayers.add(spec.source);

          this._map.map.on("click", spec.source, (e) => {

            if (e.features[0]) {

              spec.onClick(e.features[0]);

            }

          });

        }

      }

    }

    async _clearLayers(specs) {

      if (!specs || !this._map) {

        return;

      }

      for (const spec of specs) {

        if (this._map.getGeoJSON(spec.source)) {

          await this._map.setGeoJSON(
            spec.source,
            { type: "FeatureCollection", features: [] },
            { type: spec.type }
          );

        }

      }

    }


    // ==========================================================
    // Status / stats / legend / controls
    // ==========================================================

    _setStatus(text, { busy }) {

      this.state.status =
        text;

      this.state.busy =
        !!busy;

      this.statusRowEl.replaceChildren(
        window.WebGeoDS.uploadStatusEl(text, this.state.busy)
      );

    }

    _renderStats() {

      const config =
        this.config;

      let rows;

      if (this.state.result && config.compute && config.compute.stats) {

        rows =
          config.compute.stats(this.state.result, this.state.inputs);

      } else if (this.state.inspectValue && config.inspect && config.inspect.stats) {

        rows =
          config.inspect.stats(this.state.inspectValue);

      } else {

        rows =
          config.emptyStats || [["—", "Upload a file or load the example above"]];

      }

      this.statsEl.replaceChildren(
        window.WebGeoDS.statCard(rows)
      );

    }

    _renderLegend() {

      const computeCfg =
        this.config.compute;

      const items =
        (this.state.result && computeCfg && computeCfg.legend)
          ? computeCfg.legend(this.state.result)
          : null;

      this.legendWrapEl.replaceChildren(
        window.WebGeoDS.legend(items)
      );

    }

    // Declarative counterpart to graph-diagram.js's renderForceGraph,
    // for the common case of a diagram in layout.sidePanel -- keeps
    // Dashboard's own dependency on graph-diagram.js OPTIONAL (the
    // same `?.()` pattern already used for window.WebGeoDS.track
    // throughout this file, not an import/require): a page that never
    // configures `compute.diagram` never needs graph-diagram.js
    // loaded at all, and one that does gets a clear "not a function"
    // error if it forgot to, rather than Dashboard silently no-oping.
    //
    // config shape: `diagram: { nodes: value => features, links:
    // value => features, ...anything else renderForceGraph()'s own
    // options accept (nodeColor, linkColor, onNodeClick, ...) }`.
    //
    // Renders into a dedicated CHILD of sidePanelEl (`_diagramSlotEl`,
    // created on first use — see roadmap-acquisizione.md, "second
    // Dashboard tool needs its own sidePanel content alongside the
    // diagram"), not sidePanelEl directly: renderForceGraph() wipes
    // its own container on every render (`el.replaceChildren()`), and
    // sidePanelEl is a shared slot a tool's own `compute.onResult` can
    // ALSO put something in (e.g. a second Vega-Lite chart below the
    // diagram, see network-from-lines.qmd) — sidePanelEl itself is
    // only switched to a flex column here, and only for a tool that
    // actually uses compute.diagram, so a diagram-less tool (e.g. one
    // whose onResult renders straight into sidePanelEl, like Spatial
    // Classifier's chart) sees no change at all.
    _renderDiagram(diagramCfg, value) {

      this._diagram?.destroy();

      this._diagram =
        null;

      if (!diagramCfg || !this.sidePanelEl || !value) {

        return;

      }

      if (!this._diagramSlotEl) {

        this.sidePanelEl.style.display =
          "flex";

        this.sidePanelEl.style.flexDirection =
          "column";

        this.sidePanelEl.style.gap =
          "8px";

        this._diagramSlotEl =
          document.createElement("div");

        this._diagramSlotEl.style.cssText =
          "flex: 1 1 auto; min-height: 0;";

        // prepend, not append: keeps the diagram first regardless of
        // whether a sibling (e.g. a chart slot) was already added by
        // the tool's own onResult on an earlier compute.
        this.sidePanelEl.prepend(
          this._diagramSlotEl
        );

      }

      this._diagram =
        window.WebGeoDS.renderForceGraph?.(
          this._diagramSlotEl,
          { nodes: diagramCfg.nodes(value), links: diagramCfg.links(value) },
          diagramCfg
        ) ?? null;

    }

    _readInputs() {

      const out = {};

      for (const [name, el] of Object.entries(this._inputEls)) {

        if (el.type === "checkbox") {

          out[name] =
            el.checked;

        } else if (el.tagName === "SELECT") {

          out[name] =
            el.value;

        } else {

          out[name] =
            Number(el.value);

        }

      }

      return out;

    }

    // Also re-renders the status row -- this is the single place
    // every entry point (_queue's start/finally, and _runInspectInner
    // indirectly via loadExample/handleFiles) converges after a state
    // change, so the status text set just before calling this is
    // always what ends up on screen next.
    _syncControls() {

      const ready =
        !!this.state.inspectValue;

      this.statusRowEl.replaceChildren(
        window.WebGeoDS.uploadStatusEl(this.state.status, this.state.busy)
      );

      if (this._computeBtn) {

        this._computeBtn.disabled =
          this.state.busy || !ready;

      }

      if (this._downloadBtn) {

        this._downloadBtn.disabled =
          this.state.busy || !this.state.result;

      }

      for (const el of Object.values(this._inputEls)) {

        el.disabled =
          this.state.busy;

      }

    }


    // ==========================================================
    // Destroy
    // ==========================================================

    destroy() {

      if (this._map) {

        this._map.destroy();

      }

      _instances.delete(
        this.config.tool
      );

      this.root.remove();

    }

  }


  // ============================================================
  // Public WebGeoDS API
  // ============================================================

  window.WebGeoDS.Dashboard =
    WebGeoDSDashboard;


})();
